// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Toyota_SmartRFID

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
lv_obj_t *ui_WelcomeScreen;
lv_obj_t *ui_ToyotaImg;
lv_obj_t *ui_TruckImg;
lv_obj_t *ui_SigninBtn;
lv_obj_t *ui_SigninLabel;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_toyota_forklift_truck_400x[1] = {&ui_img_toyota_forklift_truck_400x360_png};
const lv_img_dsc_t *ui_imgset_toyota_forklift_truck_417x[1] = {&ui_img_toyota_forklift_truck_417x374_png};
const lv_img_dsc_t *ui_imgset_toyota_logo_170x[1] = {&ui_img_toyota_logo_170x93_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_WelcomeScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_WelcomeScreen);
}
