// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Toyota_SmartRFID

#ifndef _AES_TOYOTA_SMARTRFID_UI_H
#define _AES_TOYOTA_SMARTRFID_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
extern lv_obj_t *ui_WelcomeScreen;
extern lv_obj_t *ui_ToyotaImg;
extern lv_obj_t *ui_TruckImg;
extern lv_obj_t *ui_SigninBtn;
extern lv_obj_t *ui_SigninLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_toyota_logo_170x93_png);   // assets\Toyota_logo_170x93.png
LV_IMG_DECLARE( ui_img_toyota_forklift_truck_400x360_png);   // assets\Toyota_Forklift_truck_400x360.png
LV_IMG_DECLARE( ui_img_toyota_forklift_truck_417x374_png);   // assets\Toyota_Forklift_truck_417x374.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
