// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Smart_RFID_Display

#ifndef _UI_COMP_BUTTON1_H
#define _UI_COMP_BUTTON1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button1
#define UI_COMP_BUTTON1_BUTTON1 0
#define UI_COMP_BUTTON1_LABEL4 1
#define _UI_COMP_BUTTON1_NUM 2
lv_obj_t *ui_Button1_create(lv_obj_t *comp_parent);
void ui_event_comp_Button1_Button1( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
