// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Smart_RFID_Display

#ifndef _UI_COMP_BUTTON0_H
#define _UI_COMP_BUTTON0_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button0
#define UI_COMP_BUTTON0_BUTTON0 0
#define UI_COMP_BUTTON0_LABEL0 1
#define _UI_COMP_BUTTON0_NUM 2
lv_obj_t *ui_Button0_create(lv_obj_t *comp_parent);
void ui_event_comp_Button0_Button0( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
