// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Smart_RFID_Display

#include "../ui.h"


// COMPONENT Button2

lv_obj_t *ui_Button2_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Button2;
cui_Button2 = lv_btn_create(comp_parent);
lv_obj_set_width( cui_Button2, 75);
lv_obj_set_height( cui_Button2, 75);
lv_obj_set_x( cui_Button2, lv_pct(0) );
lv_obj_set_y( cui_Button2, lv_pct(-60) );
lv_obj_set_align( cui_Button2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( cui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Button2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Button2, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_Button2, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label3;
cui_Label3 = lv_label_create(cui_Button2);
lv_obj_set_width( cui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label3,"2");
lv_obj_set_style_text_font(cui_Label3, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON2_NUM);
children[UI_COMP_BUTTON2_BUTTON2] = cui_Button2;
children[UI_COMP_BUTTON2_LABEL3] = cui_Label3;
lv_obj_add_event_cb(cui_Button2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Button2, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Button2_create_hook(cui_Button2);
return cui_Button2; 
}

