// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Smart_RFID_Display

#include "../ui.h"

void ui_comp_Button0_create_hook( lv_obj_t * comp)
{
}

void ui_comp_Button1_create_hook( lv_obj_t * comp)
{
}

void ui_comp_Button2_create_hook( lv_obj_t * comp)
{
}
