// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Smart_RFID_Display

#include "../ui.h"


void ui_event_comp_Button0_Button0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_Button0 = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn0_clicked( e );
}
}

// COMPONENT Button0

lv_obj_t *ui_Button0_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Button0;
cui_Button0 = lv_btn_create(comp_parent);
lv_obj_set_width( cui_Button0, 75);
lv_obj_set_height( cui_Button0, 75);
lv_obj_set_x( cui_Button0, lv_pct(0) );
lv_obj_set_y( cui_Button0, lv_pct(-15) );
lv_obj_set_align( cui_Button0, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( cui_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Button0, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Button0, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_Button0, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label0;
cui_Label0 = lv_label_create(cui_Button0);
lv_obj_set_width( cui_Label0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label0, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label0,"0");
lv_obj_set_style_text_font(cui_Label0, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON0_NUM);
children[UI_COMP_BUTTON0_BUTTON0] = cui_Button0;
children[UI_COMP_BUTTON0_LABEL0] = cui_Label0;
lv_obj_add_event_cb(cui_Button0, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Button0, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_Button0, ui_event_comp_Button0_Button0, LV_EVENT_ALL, children);
ui_comp_Button0_create_hook(cui_Button0);
return cui_Button0; 
}

