// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AES_Toyota_SmartRFID

#include "../ui.h"

void ui_WelcomeScreen_screen_init(void)
{
ui_WelcomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WelcomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ToyotaImg = lv_img_create(ui_WelcomeScreen);
lv_img_set_src(ui_ToyotaImg, &ui_img_toyota_logo_170x93_png);
lv_obj_set_width( ui_ToyotaImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ToyotaImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ToyotaImg, 0 );
lv_obj_set_y( ui_ToyotaImg, 50 );
lv_obj_set_align( ui_ToyotaImg, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ToyotaImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ToyotaImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TruckImg = lv_img_create(ui_WelcomeScreen);
lv_img_set_src(ui_TruckImg, &ui_img_toyota_forklift_truck_400x360_png);
lv_obj_set_width( ui_TruckImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TruckImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TruckImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TruckImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TruckImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SigninBtn = lv_btn_create(ui_WelcomeScreen);
lv_obj_set_width( ui_SigninBtn, 240);
lv_obj_set_height( ui_SigninBtn, 50);
lv_obj_set_x( ui_SigninBtn, 0 );
lv_obj_set_y( ui_SigninBtn, -120 );
lv_obj_set_align( ui_SigninBtn, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_SigninBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SigninBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SigninBtn, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SigninBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SigninBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_SigninBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SigninBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_SigninBtn, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_SigninBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SigninLabel = lv_label_create(ui_SigninBtn);
lv_obj_set_width( ui_SigninLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SigninLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SigninLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SigninLabel,"Sign in");
lv_obj_set_style_text_color(ui_SigninLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SigninLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SigninLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SigninLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

}
